[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/webhooks/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production]
variables = { NODE_ENV = "production" }

[environments.staging]
variables = { NODE_ENV = "staging" }

# Build configuration
[[services]]
name = "shopify-order-printer"
source = "."

[services.build]
buildCommand = "npm run build"
startCommand = "npm start"

[services.variables]
PORT = "3000"
NODE_ENV = "production"

# Health check configuration
[services.healthcheck]
path = "/api/webhooks/health"
interval = 30
timeout = 10
retries = 3